INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Hafieludin Yusuf', 'Rizana' , ' male ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-JP' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 1);
INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Hafieludin Yusuf', 'Rizana' , ' male ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-JP' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 1);
INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Hafieludin Yusuf', 'Rizana' , ' male ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-JP' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 1);
INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Agus', 'Jamaluddin' , ' female ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-AN' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 2);
INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Agus', 'Jamaluddin' , ' female ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-AN' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 2);
INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Agus', 'Jamaluddin' , ' female ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-AN' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 2);
INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Darth', 'Vader' , ' male ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-AN' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 2);
INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Darth', 'Vader' , ' male ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-AN' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 2);
INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Darth', 'Vader' , ' male ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-AN' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 3);
INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Anakin', 'Skywalker' , ' male ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-AN' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 3);
INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Anakin', 'Skywalker' , ' male ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-AN' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 3);
INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Anakin', 'Skywalker' , ' male ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-AN' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 4);
INSERT INTO T_EMPLOYEE  (EMP_FNAME , EMP_LNAME , EMP_GENDER  , EMP_DOB  , EMP_NATIONAL  , EMP_MARITAL , EMP_PHONE , EMP_SUB_DIV  , EMP_STATUS , EMP_HIRE_DATE , EMP_GRADE , EMP_DIV  , EMP_EMAIL , EMP_ISACTIVE ,EMP_LOCATION )
VALUES ('Anakin', 'Skywalker' , ' male ','2017-03-03', 'Indonesian' , 'single' , '081334272304' , 'Ruby bootcamp' , ' contract' , '2017-03-03', 'SE-AN' , 'BTPN' , 'hafieluyr@gmail.com' ,true, 3);
